### ISSUE TITLE
GPLv3

### ISSUE THREAD

**Issue by EastArctica** [alfonsamg/QuizizzScript#1]
[Deleted]

**Comment by MagicRB** [comment]
Have you actually read the GPLv3 license? One of the 4 fundamental  freedoms is the freedom to redistribute and modify the source

**Comment by EastArctica** [comment]
Yes, Have you noticed the fact that I never filed a DMCA takedown because I realized that. I put this comment on a few others but I guess I forgot to close this one. (Closed due to invalidity)
